### ISSUE TITLE
Forge Microblock render issue on move

### ISSUE THREAD

**Issue by SpeedF12** [rwtema/FunkyLocomotion#42]
Seems that there is a render issue with the microblocks when moved, they are still there however I have to leave the age or log out and then re-enter for them to render again.  I have updated both Forge MultiPart and Funky Locomotion to their latest versions,

Forge Multipart - 1.1.1.320
Funky Locomotion - 1.7.10-beta-4

![before](https://cloud.githubusercontent.com/assets/8352388/5692847/2d963844-98c3-11e4-9d0d-8eb72ab4603d.PNG)

![after](https://cloud.githubusercontent.com/assets/8352388/5692849/3508fb0c-98c3-11e4-905e-698b72a3d704.PNG)

Let me know if you need any other info!

Thanks for thje awesome mods!

Wade

**Comment by SpeedF12** [comment]
Just thought I would also include that this seemed to happen after upgrading forge to 10.13.2.1284 from 10.13.2.1236, prior to it seemed to work just fine.

**Comment by Linkinexe** [comment]
Can onfirm this issue also on forge .1234

**Comment by SpeedF12** [comment]
It might be extra utilities then as that was the only other mod I updated at the same time, I know I did have it working with forge 1284, prior to updating Forge, Funky Locomotion and Extra Utilities.

Current version of Extra Utilities is 1.2.1
Previous version was 1.2.0

**Comment by SpeedF12** [comment]
This issue is resolved by updating Forge to .1286 allowing support for mass tileentity update.

Marking as closed
