### ISSUE TITLE
Client crash when a Dim unloads [Beta 5b]

### ISSUE THREAD

**Issue by Error998** [rwtema/FunkyLocomotion#66]
Environment: Multiplayer
Forge: 10.13.3.1381
Mod Version: funky-locomotion-1.7.10-beta-5b
Reproducible: Yes

TP from one dimension to another that cause the dim to unload, client will crash.

Crash Report: http://pastebin.com/APh9nDZp

**Comment by maruohon** [comment]
I just got the same crash.
Calling MinecraftServer.getServer() on the client returns null, thus the NPE.

**Comment by xannor** [comment]
I got the same crash on server exit.

**Comment by daniel-dsouza** [comment]
Same error.

java.lang.NullPointerException: Unexpected error
	at com.rwtema.funkylocomotion.fakes.FakeWorldClient$FakeWorldManager.onDimensionUnload(FakeWorldClient.java:254)
