### ISSUE TITLE
WorldLoad events fired for FakeWorldClient

### ISSUE THREAD

**Issue by nallar** [rwtema/FunkyLocomotion#71]
In commit 5286d7fb0e9d57ef6e022e7, the fake world was changed to extend WorldClient.

Due to this, world load events are fired for every FakeWorldClient instance. The corresponding WorldUnload event is never fired.

Even if the WorldUnload event was fired, this still isn't great - mods shouldn't be receiving a world load event for the fake world!

Some solutions:
- Fire the WorldUnload event (not a good idea as above)
- Don't extend WorldClient (does it need to be a WorldClient?)
- Use a transformer to prevent that event from being fired for FakeWorldClient by adding a hook to WorldClient's constructor (Factorization already does this, you may conflict with their transformer!)
- Get Forge to add a way to prevent that event from firing (add extra WorldClient constructor which doesn't fire it?)

**Comment by LunNova** [comment]
closing to clear this from the issues page as nothing's every going to happen about it
